#ifndef WOLF_CONFIG_H
#define WOLF_CONFIG_H
#define CONFIG_IPFILTER 0
#define ETHERNET
#define LINK_MTU 1536
#define LINK_MTU_MIN 64U
#define MAX_TCPSOCKETS 2
#define MAX_UDPSOCKETS 1
#define MAX_ICMPSOCKETS 1
#define RXBUF_SIZE (2 * 1024)
#define TXBUF_SIZE (2 * 1024)
#define MAX_NEIGHBORS 4
#define WOLFIP_MAX_INTERFACES 1
#define WOLFIP_ENABLE_FORWARDING 0
#define WOLFIP_ENABLE_LOOPBACK 0
#undef WOLFIP_ENABLE_HTTP
#define WOLFIP_POSIX_TCPDUMP 0
#define WOLFIP_USE_VDE 0
#endif